from .connect import connect
from .insert import insert
from .select import getDiscogsAlbums
from .select import getSources
from .select import getLargeImages
from .update import addYear
from .update import addImage
from .update import setImageResizedTrue
from .insert import discogsApiCalled
